import fsPromises from "fs/promises";
import path from "path";
import type { StorageResponse } from "../interfaces/StorageTypes.js";
import { STORAGE_MESSAGES } from "../constants/storageMessages.js";
import { handleStorageError } from "./Utils.js";

export class LocalStorageHelper {
  private readonly rootDir: string;
  private readonly baseUrl: string;

  constructor(rootDir: string, baseUrl: string) {
    if (!rootDir) {
      throw new Error(STORAGE_MESSAGES.ERRORS.ROOT_DIR_REQUIRED);
    }
    if (!baseUrl) {
      throw new Error(STORAGE_MESSAGES.ERRORS.BASE_URL_REQUIRED);
    }
    this.rootDir = path.resolve(rootDir);
    this.baseUrl = baseUrl.replace(/\/$/, ""); // remove trailing slash
  }

  // Added over kareez: a path must resolve inside rootDir. Every path written
  // here is generated by the API, but a stored path is still data from the
  // database, and "../" in one must never reach an arbitrary file on the box.
  getFullPath(relativePath: string) {
    const full = path.resolve(this.rootDir, relativePath);
    if (full !== this.rootDir && !full.startsWith(this.rootDir + path.sep)) {
      throw new Error(STORAGE_MESSAGES.ERRORS.PATH_OUTSIDE_ROOT);
    }
    return full;
  }

  buildResponse(success: boolean, message: string, relativePath: string): StorageResponse {
    const cleanedPath = relativePath.replace(/\\/g, "/").replace(/^\/+/, "");
    const url = `${this.baseUrl}/${cleanedPath}`;
    return { success, message, path: cleanedPath, url };
  }

  handleError(action: string, error: unknown, filePath: string): StorageResponse {
    return handleStorageError(action, error, filePath);
  }

  async ensureDirExists(fullPath: string) {
    // Make sure to create directory, not the file path itself
    await fsPromises.mkdir(path.dirname(fullPath), { recursive: true });
  }
}
